### ISSUE TITLE
Man pages are not colorized on all systems

### ISSUE THREAD

**Issue by bricewge** [zlsun/solarized-man#3]
On NixOS (and probably [OpenSUSE](https://github.com/robbyrussell/oh-my-zsh/issues/4543#issuecomment-275883508) and [Gentoo](https://unix.stackexchange.com/questions/6010/colored-man-pages-not-working-on-gentoo?rq=1)) this plugin doesn't work out-of-the-box, but it works on other systems: Arch, macOS, ...

The fix is to set this variable `GROFF_NO_SGR=1` as explained [here](https://unix.stackexchange.com/questions/6010/colored-man-pages-not-working-on-gentoo?rq=1#comment7916_6357). It would be nice to have it by default in this plugin, however I'm not sure it will not broke some systems. I have currently tested it on Archlinux where this didn't broke the colorization. What do you think about adding this variable to the man function?

**Comment by zlsun** [comment]
Fixed in #2 .
